In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
data = pd.read_excel('C:\\Project -DS\\DEXINUS (1).xls') #skiprows = range(0,10)
data

      observation_date  DEXINUS
0           1973-01-02     8.02
1           1973-01-03     8.02
2           1973-01-04     8.00
3           1973-01-05     8.01
4           1973-01-08     8.00
...                ...      ...
12644       2021-06-21    74.18
12645       2021-06-22    74.37
12646       2021-06-23    74.13
12647       2021-06-24    74.14
12648       2021-06-25    74.14

[12649 rows x 2 columns]

In [3]:
data = data.rename({'observation_date':'date','DEXINUS':'rate'},axis=1)

In [4]:
data.ffill(inplace=True)

In [5]:
data.isnull().sum()

date    0
rate    0
dtype: int64

In [6]:
# extract month and year from dates
data['month'] = pd.DatetimeIndex(data['date']).month
data['year'] =  pd.DatetimeIndex(data['date']).year

#data1["month"] = data1.Date.dt.strftime("%b") # month extraction
#data1["year"] = data1.Date.dt.strftime("%y") # year extraction

# create a sequence of numbers
data['Series'] = np.arange(1,len(data)+1)# drop unnecessary columns and re-arrange 
data = data[['Series', 'year', 'month', 'rate']] 

# check the head of the dataset
data.head()

   Series  year  month  rate
0       1  1973      1  8.02
1       2  1973      1  8.02
2       3  1973      1  8.00
3       4  1973      1  8.01
4       5  1973      1  8.00

In [7]:
data.tail()

       Series  year  month   rate
12644   12645  2021      6  74.18
12645   12646  2021      6  74.37
12646   12647  2021      6  74.13
12647   12648  2021      6  74.14
12648   12649  2021      6  74.14

In [8]:
# split data into train-test set
train = data[data['year'] < 2019]
test = data[data['year'] >= 2019]
# check shape
train.shape, test.shape

((12000, 4), (649, 4))

In [9]:
# import the regression module
from pycaret.regression import *
# initialize setup
s = setup(data = train , test_data = test, target = 'rate',
          fold_strategy = 'timeseries', numeric_features = ['year', 'Series'],
          fold = 3, transform_target = True, session_id = 123)

In [10]:
best = compare_models(sort = 'MAE')

In [11]:
prediction_holdout = predict_model(best);